### ISSUE TITLE
求问

### ISSUE THREAD

**Issue by sakura521** [guoday/Tencent2018_Lookalike_Rank7th#2]
train_df[f + '_uid'] = train_df[f] + train_df['uid'] * 10000000
dev_df[f + '_uid'] = dev_df[f] + dev_df['uid'] * 10000000
这个交叉特征是怎么做的？实在是看不懂啊？难道是两个特征值相加？？？

**Comment by guoday** [comment]
如果我们需要表示一个交叉特征(f,uid)，我们只需要找一个一一映射函数g将(f_ID,uid_ID)映射成一个ID就够了，而在此任务中，我们知道f的ID不会大于10000000，那么我们可以把(13,212)映射成2120000013。反过来，如果给定2120000013，我们反向得到(13,212)。那么(13,212)与2120000013就是等价的，既然如此，我们为什么不用int来表示交叉特征呢？

**Comment by sakura521** [comment]
> 如果我们需要表示一个交叉特征(f,uid)，我们只需要找一个一一映射函数g将(f_ID,uid_ID)映射成一个ID就够了，而在此任务中，我们知道f的ID不会大于10000000，那么我们可以把(13,212)映射成2120000013。反过来，如果给定2120000013，我们反向得到(13,212)。那么(13,212)与2120000013就是等价的，既然如此，我们为什么不用int来表示交叉特征呢？

**Comment by sakura521** [comment]
懂起了，谢谢，不过代码真的好难读懂哦orz= =
