### ISSUE TITLE
训练模型的问题

### ISSUE THREAD

**Issue by sakura521** [guoday/Tencent2018_Lookalike_Rank7th#4]
exfm_logit=self._build_extreme_FM(hparams, x, res=True, direct=False, bias=True, reduce_D=True, f_dim=2)[:,0] # shape=(?,)

你好，请问训练这个部分的时候参数是怎么设定，我抽取了80万融合之后的数据训练，可是auc只有0.4955...，我猜测是因为模型迭代训练出了问题，有可能训练数据集只训练了一次，可是不知哪个参数是训练迭代次数接口，训练出来dev只有15步....整个训练过程用了60s左右，请大佬解惑，感激不尽！

**Comment by guoday** [comment]
80万数据太少了，batchsize=4096，80W/4096=195次迭代。训练参数在src/train.py设定
