### ISSUE TITLE
extract_features.py下的single_features函数

### ISSUE THREAD

**Issue by Woooosz** [guoday/Tencent2018_Lookalike_Rank7th#5]
请问
        word2index[s]={}
        for idx,val in enumerate(index):
            word2index[s][val]=idx+2
为什么要idx + 2呢，此处'+2'是基于什么考量呢？

**Comment by guoday** [comment]
这里有两个特殊符号，一个是'<unk>',一个是'<pad>'。因为测试集中会有一些不可见的id，所以都置为<unk>，而多值特征中，要填充到一定长度，所以就有'<pad>'

**Comment by ShawnyXiao** [comment]
您好，这里的回答好像没有正常显示。

读了代码，理解了一下。其中用`id=0`表示了多值特征中需要填充的元素，用`id=1`表示了特征中的null值。是否如同理解的一样，麻烦指正一下，非常感谢。

**Comment by guoday** [comment]
> 您好，这里的回答好像没有正常显示。
> 读了代码，理解了一下。其中用id=0表示了多值特征中需要填充的元素，用id=1表示了特征中的null值。是否如同理解的一样，麻烦指正一下，非常感谢。

是的

**Comment by ShawnyXiao** [comment]
感谢您的回答
