### ISSUE TITLE
关于 kv memory 

### ISSUE THREAD

**Issue by BigAN** [guoday/Tencent2018_Lookalike_Rank7th#6]
请教一下, 在您的代码中, 没有找到这部分的实现, 能进一步的解释一下吗?

**Comment by guoday** [comment]
这代码的KVMem被我删掉了，因为复赛中没用到连续值。你可以参考BDC_2018的代码，里面有KVMem。或者你也可以关注ctrNet-tool，后续会推出工具包，包含该特性

**Comment by BigAN** [comment]
谢谢.

**Comment by BigAN** [comment]
恩, 我再问一下. 这种处理方式, 会比归一化方法号多少呢?

**Comment by guoday** [comment]
这个很难说，因为腾讯复赛我没用。但在最近的icme比赛中，也是AUC的评测指标，效果是从0.7387786806->0.7395302806，大概一个千分点。其实也算提升很大了

**Comment by BigAN** [comment]
赞
