### ISSUE TITLE
训练loss改为auc

### ISSUE THREAD

**Issue by cookie54sun** [guoday/Tencent2018_Lookalike_Rank7th#7]
你好，由于比赛的指标为auc,所以我把代码里的self.cost做了如下改变：
![image](https://user-images.githubusercontent.com/47913956/60315341-ca529800-9998-11e9-85c0-388c055ce2bc.png)
但是会报错：
![image](https://user-images.githubusercontent.com/47913956/60315364-e22a1c00-9998-11e9-8af6-0ad8fa4185b8.png)
请问大佬这个问题应该怎么解决？感谢！

**Comment by cookie54sun** [comment]
我应该知道时为什么了，因为auc不可导（；´д｀）ゞ

**Comment by guoday** [comment]
> 我应该知道时为什么了，因为auc不可导（；´д｀）ゞ

恩，但其实用logloss就行，一般auc的指标的都是用logloss

**Comment by cookie54sun** [comment]
感谢回复~还想问一个问题，请问你在跑代码的时候碰到过 Found Inf or NaN global norm这种问题吗？
![image](https://user-images.githubusercontent.com/47913956/61292405-b5cd2700-a803-11e9-9f3a-750cafc00675.png)
有时候把学习率调小了就可以解决，难道是正好到了目标函数曲线上梯度很大的点？

**Comment by guoday** [comment]
应该是学习率过大，一般来说我默认的学习率就差不多了，过大有可能梯度太大
